Repository dart-lang/site-webdev, pull requests merged in 2018-07, with the labels that each got.

#1673 [4.x] Deploy to webdev-angular4-dartlang-org
  .firebaserc
  .travis.yml
  _config.yml
  src/_assets/javascripts/ng/directives/live-example.js
  src/_data/pkg-vers.json
  src/_includes/navigation-main.html
Labels: cla: yes

#1674 Upgrade to NG 5-beta part 2 of 2 (for ACX)
  .travis.yml
  examples/acx/lottery/1-base/pubspec.lock
  examples/acx/lottery/2-starteasy/pubspec.lock
  examples/acx/lottery/2-starteasy/pubspec.yaml
  examples/acx/lottery/3-usebuttons/pubspec.lock
  examples/acx/lottery/3-usebuttons/pubspec.yaml
  examples/acx/lottery/4-final/pubspec.lock
  examples/acx/lottery/4-final/pubspec.yaml
  examples/fetch_data/pubspec.lock
  examples/html/pubspec.lock
  examples/ng/api/common/pipes/pubspec.lock
  examples/ng/api/core/ngzone/pubspec.lock
  examples/ng/doc/architecture/pubspec.lock
  examples/ng/doc/attribute-directives/pubspec.lock
  examples/ng/doc/component-styles/pubspec.lock
  examples/ng/doc/dependency-injection/pubspec.lock
  examples/ng/doc/displaying-data/pubspec.lock
  examples/ng/doc/forms/pubspec.lock
  examples/ng/doc/hierarchical-dependency-injection/pubspec.lock
  examples/ng/doc/lifecycle-hooks/pubspec.lock
  examples/ng/doc/pipes/pubspec.lock
  examples/ng/doc/quickstart/pubspec.lock
  examples/ng/doc/router/pubspec.lock
  examples/ng/doc/security/pubspec.lock
  examples/ng/doc/server-communication/pubspec.lock
  examples/ng/doc/structural-directives/pubspec.lock
  examples/ng/doc/structural-directives/pubspec.yaml
  examples/ng/doc/template-syntax/pubspec.lock
  examples/ng/doc/template-syntax/pubspec.yaml
  examples/ng/doc/toh-0/pubspec.lock
  examples/ng/doc/toh-1/pubspec.lock
  examples/ng/doc/toh-2/pubspec.lock
  examples/ng/doc/toh-3/pubspec.lock
  examples/ng/doc/toh-4/pubspec.lock
  examples/ng/doc/toh-5/pubspec.lock
  examples/ng/doc/toh-6/pubspec.lock
  examples/ng/doc/user-input/pubspec.lock
  examples/util/pageloader/pubspec.lock
  gulp/api.js
  pubspec.lock
  src/_codelabs/angular_components/2-starteasy.md
  src/_data/pkg-vers.json
  src/_data/pubspec.lock
  src/_data/pubspec.yaml
Labels: cla: yes

#1675 [4.x] Set banner and remove 3.x from version menu
  src/_includes/banner.html
  src/_includes/navigation-main.html
Labels: cla: yes

#1676 chore: no-robots for 5-dev and other config prep
  .github/_PULL_REQUEST_TEMPLATE.md
  .travis.yml
  _config.yml
Labels: Infrastructure, cla: yes

#1677 [5-dev] Adjust banner
  _config.yml
  src/_includes/banner-top.md
  src/_includes/banner.html
  src/index.html
Labels: cla: yes

#1678 Server switch prep: update banner
  .travis.yml
  _config.yml
  src/_includes/banner.html
  src/changelog.md
  src/version.md
Labels: Infrastructure, cla: yes

#1681 Adjust version menu labels, and ensure 4.x is showing
  src/_includes/navigation-main.html
Labels: Infrastructure, cla: yes

#1682 chore: bundle update
  Gemfile.lock
Labels: Infrastructure, cla: yes

#1685 chore: update gems
  Gemfile.lock
Labels: Infrastructure, cla: yes

#1687 Fix article index page listings
  src/_articles/index.md
  src/_articles/low-level-html/embedding-in-html.md
  src/_articles/low-level-html/index.md
  src/_articles/performance/event-loop.md
  src/_articles/performance/index.md
  src/_includes/article_summary.html
  src/_plugins/filters.rb
Labels: Infrastructure, cla: yes

#1688 Split component testing across two Travis jobs
  .travis.yml
Labels: Infrastructure, cla: yes

#1692 Map v4 site og:image to v5 image
  firebase.json
Labels: Infrastructure, cla: yes

#1691 Update link to deferred loading information
  src/angular/guide/deployment.md
Labels: cla: yes

#1693 Fix 404s to /examples/ng/**
  firebase.json
Labels: Infrastructure, cla: yes

#1694 chore: 404 page tweaks
  src/404.html
  src/404.md
  src/_layouts/error.html
  src/api/index.md
Labels: cla: yes

#1695 Ensure API page directive launches!
  src/api/index.md
Labels: Infrastructure, cla: yes

#1696 Document @Component `exports` parameter
  examples/ng/doc/template-syntax/lib/app_component.dart
  src/angular/guide/template-syntax.md
  src/changelog.md
Labels: Angular, Docs, cla: yes

#1701 Example(fetch_data): ensure styles.css gets committed
  examples/.gitignore
  examples/fetch_data/web/styles.css
Labels: cla: yes

#1706 Add links to debugging page
  src/_guides/get-started.md
  src/_guides/index.md
Labels: cla: yes

#1708 Upgrade to Angular 5-beta+1, part 1 of 2
  .travis.yml
  examples/acx/lottery/1-base/pubspec.lock
  examples/acx/lottery/2-starteasy/pubspec.lock
  examples/acx/lottery/3-usebuttons/pubspec.lock
  examples/acx/lottery/4-final/pubspec.lock
  examples/fetch_data/pubspec.lock
  examples/html/pubspec.lock
  examples/ng/api/common/pipes/pubspec.lock
  examples/ng/api/core/ngzone/pubspec.lock
  examples/ng/doc/architecture/pubspec.lock
  examples/ng/doc/attribute-directives/pubspec.lock
  examples/ng/doc/component-styles/pubspec.lock
  examples/ng/doc/dependency-injection/pubspec.lock
  examples/ng/doc/displaying-data/pubspec.lock
  examples/ng/doc/forms/pubspec.lock
  examples/ng/doc/hierarchical-dependency-injection/pubspec.lock
  examples/ng/doc/lifecycle-hooks/pubspec.lock
  examples/ng/doc/pipes/pubspec.lock
  examples/ng/doc/quickstart/pubspec.lock
  examples/ng/doc/router/pubspec.lock
  examples/ng/doc/security/pubspec.lock
  examples/ng/doc/server-communication/pubspec.lock
  examples/ng/doc/structural-directives/pubspec.lock
  examples/ng/doc/template-syntax/pubspec.lock
  examples/ng/doc/toh-0/pubspec.lock
  examples/ng/doc/toh-1/pubspec.lock
  examples/ng/doc/toh-2/pubspec.lock
  examples/ng/doc/toh-3/pubspec.lock
  examples/ng/doc/toh-4/pubspec.lock
  examples/ng/doc/toh-5/pubspec.lock
  examples/ng/doc/toh-6/pubspec.lock
  examples/ng/doc/user-input/pubspec.lock
  examples/util/pageloader/pubspec.lock
  pubspec.lock
  src/_data/pkg-vers.json
  src/_data/pubspec.lock
  src/_data/pubspec.yaml
Labels: cla: yes

#1714 Dependency injection page cleanup
  examples/ng/doc/dependency-injection/e2e-spec.ts
  examples/ng/doc/dependency-injection/lib/app_component.dart
  examples/ng/doc/dependency-injection/lib/src/car/car.dart
  examples/ng/doc/dependency-injection/lib/src/heroes/hero_service.dart
  examples/ng/doc/dependency-injection/lib/src/heroes/hero_service_1.dart
  examples/ng/doc/dependency-injection/lib/src/heroes/hero_service_2.dart
  examples/ng/doc/dependency-injection/lib/src/heroes/heroes_component.dart
  examples/ng/doc/dependency-injection/lib/src/logger_service.dart
  examples/ng/doc/dependency-injection/lib/src/test_component.dart
  examples/ng/doc/dependency-injection/lib/src/user_service.dart
  examples/ng/doc/dependency-injection/test/hero_list_component_test.dart
  examples/ng/doc/dependency-injection/web/main_1.dart
  examples/ng/doc/package-lock.json
  gulp/e2e.js
  src/angular/guide/dependency-injection.md
Labels: Angular, Docs, Examples, cla: yes

#1716 Hierarchical DI page: minor cleanup; drop unused imports from all examples
  examples/acx/lottery/1-base/lib/src/settings/settings.dart
  examples/acx/lottery/2-starteasy/lib/src/settings/settings.dart
  examples/acx/lottery/3-usebuttons/lib/src/settings/settings.dart
  examples/acx/lottery/4-final/lib/src/settings/settings.dart
  examples/ng/doc/architecture/lib/src/backend_service.dart
  examples/ng/doc/architecture/lib/src/hero_service.dart
  examples/ng/doc/architecture/lib/src/logger_service.dart
  examples/ng/doc/architecture/lib/src/sales_tax_service.dart
  examples/ng/doc/architecture/lib/src/tax_rate_service.dart
  examples/ng/doc/hierarchical-dependency-injection/lib/src/car_services.dart
  examples/ng/doc/hierarchical-dependency-injection/lib/src/hero_tax_return_service.dart
  examples/ng/doc/hierarchical-dependency-injection/lib/src/heroes_service.dart
  examples/ng/doc/hierarchical-dependency-injection/lib/src/villains_service.dart
  examples/ng/doc/lifecycle-hooks/lib/src/logger_service.dart
  examples/ng/doc/router/lib/src/crisis/crisis_service.dart
  examples/ng/doc/router/lib/src/crisis/dialog_service.dart
  examples/ng/doc/router/lib/src/hero/hero_service.dart
  examples/ng/doc/router/lib/src/routes.dart
  examples/ng/doc/router/lib/src/routes_1.dart
  examples/ng/doc/router/lib/src/routes_2.dart
  examples/ng/doc/router/lib/src/routes_3.dart
  examples/ng/doc/router/lib/src/routes_4.dart
  examples/ng/doc/server-communication/lib/in_memory_data_service.dart
  examples/ng/doc/server-communication/lib/src/toh/hero_service.dart
  examples/ng/doc/server-communication/lib/src/wiki/wikipedia_service.dart
  gulp/example.js
  src/angular/guide/hierarchical-dependency-injection.md
  src/angular/guide/router/1.md
  src/angular/guide/router/5.md
  src/angular/guide/server-communication.md
Labels: Angular, Examples, cla: yes

#1721 Upgrade to Angular 5-beta+2 (w/o ACX)
  examples/acx/lottery/1-base/pubspec.lock
  examples/acx/lottery/2-starteasy/pubspec.lock
  examples/acx/lottery/3-usebuttons/pubspec.lock
  examples/acx/lottery/4-final/pubspec.lock
  examples/fetch_data/pubspec.lock
  examples/html/pubspec.lock
  examples/ng/api/common/pipes/pubspec.lock
  examples/ng/api/core/ngzone/pubspec.lock
  examples/ng/doc/architecture/pubspec.lock
  examples/ng/doc/attribute-directives/pubspec.lock
  examples/ng/doc/component-styles/pubspec.lock
  examples/ng/doc/dependency-injection/pubspec.lock
  examples/ng/doc/displaying-data/pubspec.lock
  examples/ng/doc/forms/pubspec.lock
  examples/ng/doc/hierarchical-dependency-injection/pubspec.lock
  examples/ng/doc/lifecycle-hooks/pubspec.lock
  examples/ng/doc/pipes/pubspec.lock
  examples/ng/doc/quickstart/pubspec.lock
  examples/ng/doc/router/pubspec.lock
  examples/ng/doc/security/pubspec.lock
  examples/ng/doc/server-communication/pubspec.lock
  examples/ng/doc/structural-directives/pubspec.lock
  examples/ng/doc/template-syntax/pubspec.lock
  examples/ng/doc/toh-0/pubspec.lock
  examples/ng/doc/toh-1/pubspec.lock
  examples/ng/doc/toh-2/pubspec.lock
  examples/ng/doc/toh-3/pubspec.lock
  examples/ng/doc/toh-4/pubspec.lock
  examples/ng/doc/toh-5/pubspec.lock
  examples/ng/doc/toh-6/pubspec.lock
  examples/ng/doc/user-input/pubspec.lock
  examples/util/pageloader/pubspec.lock
  pubspec.lock
  src/_data/pkg-vers.json
  src/_data/pubspec.lock
  src/_data/pubspec.yaml
Labels: cla: yes

#1722 Component styles: drop template inline and link styles sections
  examples/ng/doc/component-styles/e2e-spec.ts
  examples/ng/doc/component-styles/lib/src/hero_controls_component.dart
  examples/ng/doc/component-styles/lib/src/hero_team_component.dart
  src/angular/guide/component-styles.md
  src/angular/guide/forms.md
  src/changelog.md
Labels: Angular, Docs, cla: yes

#1707 Feature the AngularDart Gallery, refresh the about page
  src/_assets/images/angular_components_example-screenshot-1.png
  src/_assets/images/angular_components_example-screenshot-2.png
  src/_assets/images/angular_components_example-screenshot.png
  src/_data/side-nav.yml
  src/components/index.md
Labels: cla: yes

#1724 Examples: reinstate component-styles tests
  .travis.yml
Labels: cla: yes

#1720 Changelog updates
  src/changelog.md
Labels: Docs, cla: yes

#1726 Examples: upgrade to ACX beta+1
  .travis.yml
  examples/acx/lottery/1-base/pubspec.lock
  examples/acx/lottery/2-starteasy/pubspec.lock
  examples/acx/lottery/3-usebuttons/pubspec.lock
  examples/acx/lottery/4-final/pubspec.lock
  examples/fetch_data/pubspec.lock
  examples/html/pubspec.lock
  examples/ng/api/common/pipes/pubspec.lock
  examples/ng/api/core/ngzone/pubspec.lock
  examples/ng/doc/architecture/pubspec.lock
  examples/ng/doc/attribute-directives/pubspec.lock
  examples/ng/doc/component-styles/pubspec.lock
  examples/ng/doc/dependency-injection/pubspec.lock
  examples/ng/doc/displaying-data/pubspec.lock
  examples/ng/doc/forms/pubspec.lock
  examples/ng/doc/hierarchical-dependency-injection/pubspec.lock
  examples/ng/doc/lifecycle-hooks/pubspec.lock
  examples/ng/doc/pipes/pubspec.lock
  examples/ng/doc/quickstart/pubspec.lock
  examples/ng/doc/router/pubspec.lock
  examples/ng/doc/security/pubspec.lock
  examples/ng/doc/server-communication/pubspec.lock
  examples/ng/doc/structural-directives/pubspec.lock
  examples/ng/doc/template-syntax/pubspec.lock
  examples/ng/doc/toh-0/pubspec.lock
  examples/ng/doc/toh-1/pubspec.lock
  examples/ng/doc/toh-2/pubspec.lock
  examples/ng/doc/toh-3/pubspec.lock
  examples/ng/doc/toh-4/pubspec.lock
  examples/ng/doc/toh-5/pubspec.lock
  examples/ng/doc/toh-6/pubspec.lock
  examples/ng/doc/user-input/pubspec.lock
  examples/util/pageloader/pubspec.lock
  pubspec.lock
  src/_data/pkg-vers.json
  src/_data/pubspec.lock
Labels: Examples, cla: yes

#1730 Use dartdoc 0.20.0
  scripts/before-install.sh
Labels: API docs, Angular, cla: yes

#1732 chore: support use of fixed site page timestamp
  _config_now.yml
  scripts/serve_local.sh
  src/_includes/page-footer.html
  src/sitemap.xml
Labels: Infrastructure, cla: yes

#1735 FIx First timers only friendly's badge address
  README.md
Labels: cla: yes

#1736 chore: unpin dartdoc version
  scripts/before-install.sh
Labels: Infrastructure, cla: yes

#1740 Angular examples cleanup
  examples/acx/lottery/1-base/lib/lottery_simulator.dart
  examples/acx/lottery/1-base/lib/src/settings/settings_component.dart
  examples/acx/lottery/1-base/lib/src/visualize_winnings/visualize_winnings.dart
  examples/acx/lottery/2-starteasy/lib/lottery_simulator.dart
  examples/acx/lottery/2-starteasy/lib/src/settings/settings_component.dart
  examples/acx/lottery/2-starteasy/lib/src/visualize_winnings/visualize_winnings.dart
  examples/acx/lottery/3-usebuttons/lib/lottery_simulator.dart
  examples/acx/lottery/3-usebuttons/lib/src/settings/settings_component.dart
  examples/acx/lottery/3-usebuttons/lib/src/visualize_winnings/visualize_winnings.dart
  examples/acx/lottery/4-final/lib/lottery_simulator.dart
  examples/acx/lottery/4-final/lib/src/settings/settings_component.dart
  examples/acx/lottery/4-final/lib/src/visualize_winnings/visualize_winnings.dart
  examples/ng/doc/lifecycle-hooks/lib/src/peek_a_boo_component.dart
  examples/ng/doc/lifecycle-hooks/lib/src/spy_directive.dart
  examples/ng/doc/router/lib/app_component.dart
  examples/ng/doc/router/lib/app_component_1.dart
  examples/ng/doc/router/lib/app_component_2.dart
  examples/ng/doc/router/lib/app_component_3.dart
  examples/ng/doc/router/lib/app_component_4.dart
  examples/ng/doc/router/lib/src/crisis/crisis_component.dart
  examples/ng/doc/router/lib/src/crisis/crisis_component_3.dart
  examples/ng/doc/router/lib/src/crisis/crisis_component_4.dart
  examples/ng/doc/router/lib/src/crisis/crisis_list_component.dart
  examples/ng/doc/router/lib/src/crisis/crisis_list_component_3.dart
  examples/ng/doc/router/lib/src/crisis/crisis_list_component_4.dart
  examples/ng/doc/router/lib/src/crisis/routes.dart
  examples/ng/doc/router/lib/src/hero/hero_component.dart
  examples/ng/doc/router/lib/src/hero/hero_component_0.dart
  examples/ng/doc/router/lib/src/hero/hero_list_component.dart
  examples/ng/doc/router/lib/src/routes.dart
  examples/ng/doc/router/lib/src/routes_1.dart
  examples/ng/doc/router/lib/src/routes_2.dart
  examples/ng/doc/router/lib/src/routes_3.dart
  examples/ng/doc/router/lib/src/routes_4.dart
  examples/ng/doc/server-communication/lib/src/toh/hero_list_component.dart
  examples/ng/doc/toh-6/lib/app_component.dart
  examples/ng/doc/toh-6/lib/src/dashboard_component.dart
  examples/ng/doc/toh-6/lib/src/hero_component.dart
  examples/ng/doc/toh-6/lib/src/hero_search_component.dart
  examples/ng/doc/toh-6/lib/src/routes.dart
  src/angular/guide/lifecycle-hooks.md
  src/angular/guide/router/1.md
  src/angular/guide/router/2.md
  src/angular/guide/router/3.md
  src/angular/guide/router/4.md
  src/angular/guide/router/5.md
  src/angular/guide/router/appendices.md
  src/angular/guide/router/index.md
  src/angular/guide/server-communication.md
  src/angular/tutorial/toh-pt6.md
Labels: Angular, Examples, cla: yes

#1739 NG Tutorial: mention analysis_options.yaml as of the "Starter App" page
  src/angular/tutorial/toh-pt0.md
  src/angular/tutorial/toh-pt1.md
  src/angular/tutorial/toh-pt2.md
  src/angular/tutorial/toh-pt3.md
  src/angular/tutorial/toh-pt4.md
  src/angular/tutorial/toh-pt6.md
Labels: Angular, Tutorials, cla: yes

#1746 Tutorial(toh-4): fix prose referring to `new`
  src/angular/tutorial/toh-pt4.md
Labels: cla: yes

#1748 Replace live-example AngularJS directive by a custom Jekyll tag
  src/_assets/javascripts/ng/directives/live-example.js
  src/_includes/head.html
  src/_plugins/example-ref.rb
  src/angular/guide/architecture.md
  src/angular/guide/attribute-directives.md
  src/angular/guide/component-styles.md
  src/angular/guide/dependency-injection.md
  src/angular/guide/displaying-data.md
  src/angular/guide/forms.md
  src/angular/guide/hierarchical-dependency-injection.md
  src/angular/guide/index.md
  src/angular/guide/lifecycle-hooks.md
  src/angular/guide/pipes.md
  src/angular/guide/router/5.md
  src/angular/guide/router/index.md
  src/angular/guide/security.md
  src/angular/guide/server-communication.md
  src/angular/guide/structural-directives.md
  src/angular/guide/template-syntax.md
  src/angular/guide/user-input.md
  src/angular/tutorial/index.md
  src/angular/tutorial/toh-pt0.md
  src/angular/tutorial/toh-pt1.md
  src/angular/tutorial/toh-pt2.md
  src/angular/tutorial/toh-pt3.md
  src/angular/tutorial/toh-pt4.md
  src/angular/tutorial/toh-pt5.md
  src/angular/tutorial/toh-pt6.md
Labels: Angular, Docs, Infrastructure, cla: yes

#1753 Upgrade SDK to 2-dev.69.5
  .travis.yml
  examples/acx/lottery/1-base/pubspec.lock
  examples/acx/lottery/2-starteasy/pubspec.lock
  examples/acx/lottery/3-usebuttons/pubspec.lock
  examples/acx/lottery/4-final/pubspec.lock
  examples/html/pubspec.lock
  examples/ng/api/common/pipes/pubspec.lock
  examples/ng/api/core/ngzone/pubspec.lock
  examples/ng/doc/architecture/pubspec.lock
  examples/ng/doc/attribute-directives/pubspec.lock
  examples/ng/doc/component-styles/pubspec.lock
  examples/ng/doc/dependency-injection/pubspec.lock
  examples/ng/doc/displaying-data/pubspec.lock
  examples/ng/doc/forms/pubspec.lock
  examples/ng/doc/hierarchical-dependency-injection/pubspec.lock
  examples/ng/doc/lifecycle-hooks/pubspec.lock
  examples/ng/doc/pipes/pubspec.lock
  examples/ng/doc/quickstart/pubspec.lock
  examples/ng/doc/router/pubspec.lock
  examples/ng/doc/security/pubspec.lock
  examples/ng/doc/server-communication/pubspec.lock
  examples/ng/doc/structural-directives/pubspec.lock
  examples/ng/doc/template-syntax/pubspec.lock
  examples/ng/doc/toh-0/pubspec.lock
  examples/ng/doc/toh-1/pubspec.lock
  examples/ng/doc/toh-2/pubspec.lock
  examples/ng/doc/toh-3/pubspec.lock
  examples/ng/doc/toh-4/pubspec.lock
  examples/ng/doc/toh-5/pubspec.lock
  examples/ng/doc/toh-6/pubspec.lock
  examples/ng/doc/user-input/pubspec.lock
  examples/util/pageloader/pubspec.lock
  src/_data/pubspec.lock
Labels: cla: yes
