Repository dart-lang/site-webdev, pull requests merged in 2018-03, with the labels that each got.

#1352 chore: prettify plugin tweak; a few more style fixes
  .travis.yml
  src/_layouts/angular.html
  src/_plugins/prettify.rb
  src/angular/guide/dependency-injection.md
  src/angular/guide/displaying-data.md
  src/angular/guide/router/5.md
  src/angular/guide/server-communication.md
  src/angular/guide/structural-directives.md
Labels: Design, Infrastructure, cla: yes

#1358 Router overview: mention directives and providers
  src/angular/guide/router/index.md
Labels: Angular, Docs, cla: yes

#1360 chore: ignore .dart_tool as of Dart 2-dev.32
  .gitignore
Labels: Infrastructure, cla: yes

#1364 chore: update pkg-vers.json
  src/_data/pkg-vers.json
  src/_data/pubspec.lock
  src/_data/pubspec.yaml
Labels: cla: yes

#1368 chore(README): update env-set.sh and site installation instructions
  .travis.yml
  README.md
  scripts/env-set.sh
Labels: Infrastructure, cla: yes

#1374 Fix external link 404s
  src/angular/guide/security.md
  src/tools/dart2js.md
  src/tools/dartdevc/faq.md
Labels: Docs, cla: yes

#1377 Update external link in docs - user data dir
  src/tools/dartium.md
Labels: cla: yes

#1379 Changelog code excerpt formatting fix
  src/_plugins/prettify.rb
  src/changelog.md
Labels: Docs, cla: yes

#1383 chore(e2e): config cleanup
  examples/ng/doc/_boilerplate/bs-config.e2e.json
  examples/ng/doc/_boilerplate/bs-config.json
  examples/ng/doc/_boilerplate/example-config.json
  examples/ng/doc/_boilerplate/package.json
  examples/ng/doc/_boilerplate/tsconfig.json
  examples/ng/doc/_boilerplate/tslint.json
  examples/ng/doc/architecture/example-config.json
  examples/ng/doc/attribute-directives/example-config.json
  examples/ng/doc/component-styles/example-config.json
  examples/ng/doc/dependency-injection/example-config.json
  examples/ng/doc/displaying-data/example-config.json
  examples/ng/doc/forms/example-config.json
  examples/ng/doc/hierarchical-dependency-injection/example-config.json
  examples/ng/doc/lifecycle-hooks/example-config.json
  examples/ng/doc/package.json
  examples/ng/doc/pipes/example-config.json
  examples/ng/doc/quickstart/example-config.json
  examples/ng/doc/router/example-config.json
  examples/ng/doc/security/example-config.json
  examples/ng/doc/server-communication/example-config.json
  examples/ng/doc/structural-directives/example-config.json
  examples/ng/doc/template-syntax/example-config.json
  examples/ng/doc/toh-0/example-config.json
  examples/ng/doc/toh-1/example-config.json
  examples/ng/doc/toh-2/example-config.json
  examples/ng/doc/toh-3/example-config.json
  examples/ng/doc/toh-4/example-config.json
  examples/ng/doc/toh-5/example-config.json
  examples/ng/doc/toh-6/example-config.json
  examples/ng/doc/user-input/example-config.json
  gulp/e2e.js
Labels: Infrastructure, cla: yes

#1373 docs(component-styles): drop native view encapsulation
  examples/ng/doc/component-styles/lib/src/quest_summary_component.dart
  src/angular/guide/component-styles.md
  src/changelog.md
Labels: Angular, Docs, cla: yes

#1389 [5-dev] Replace router guide by warning that it is being updated
  firebase.json
  src/angular/guide/router.md
  src/angular/guide/router/_index.md
Labels: cla: yes

#1390 [5-dev] Toh-5: require angular_router import earlier
  examples/ng/doc/toh-5/lib/src/heroes_component.dart
  scripts/config/linkcheck-skip-list.txt
  src/_codelabs/angular_components/2-starteasy.md
  src/angular/tutorial/toh-pt5.md
Labels: Tutorials, cla: yes

#1394 chore: ensure proper version of API docs are used locally
  gulp/api-list.js
  gulp/api.js
  gulp/pkg-vers.js
  gulpfile.js
Labels: Infrastructure, cla: yes

#1399 Interim migration guide
  src/dart-2.md
Labels: cla: yes

#1400 dart-2: Link to the dev site's changelog
  src/dart-2.md
Labels: cla: yes

#1402 chore: use code-excerpter npm package, drop local version
  gulp/example-frag.js
  gulpfile.js
  package.json
  scripts/refresh-code-excerpts.sh
  tools/doc-shredder/doc-shredder.js
  tools/doc-shredder/fileReaders/extractPathsReader.js
  tools/doc-shredder/fileReaders/regionFileReader.js
  tools/doc-shredder/notes.md
  tools/doc-shredder/processors/renderAsJadeProcessor.js
  tools/doc-shredder/processors/renderAsMarkdownProcessor.js
  tools/doc-shredder/processors/renderAsTextProcessor.js
  tools/doc-shredder/processors/shredMapProcessor.js
  tools/doc-shredder/regionExtractor.js
  tools/doc-shredder/xref-doc.json.template
  tools/doc-shredder/xref-frag.html.template
  tools/doc-shredder/xref-jade.html.template
Labels: Infrastructure, cla: yes

#1403 Dart 2 migration guide updates
  src/_data/side-nav.yml
  src/dart-2.md
Labels: cla: yes
