Repository dart-lang/site-webdev, pull requests merged in 2018-08, with the labels that each got.

#1742 Tutorial(toh-5): rework
  examples/ng/doc/toh-5/lib/app_component.dart
  examples/ng/doc/toh-5/lib/src/dashboard_component.dart
  examples/ng/doc/toh-5/lib/src/dashboard_component_2.dart
  examples/ng/doc/toh-5/lib/src/hero_component.dart
  examples/ng/doc/toh-5/lib/src/hero_list_component.css
  examples/ng/doc/toh-5/lib/src/hero_list_component.dart
  examples/ng/doc/toh-5/lib/src/route_paths.dart
  examples/ng/doc/toh-5/lib/src/routes.dart
  examples/ng/doc/toh-5/test/dashboard.dart
  examples/ng/doc/toh-5/test/dashboard_real_router.dart
  examples/ng/doc/toh-5/test/hero.dart
  examples/ng/doc/toh-5/test/heroes.dart
  src/angular/guide/router/index.md
  src/angular/guide/testing/component/routing-components.md
  src/angular/tutorial/toh-pt5.md
Labels: Angular, Tutorials, cla: yes

#1755 Example(toh-6): update to match recent changes made to toh-5
  examples/ng/doc/toh-1/analysis_options.yaml
  examples/ng/doc/toh-2/analysis_options.yaml
  examples/ng/doc/toh-3/analysis_options.yaml
  examples/ng/doc/toh-4/analysis_options.yaml
  examples/ng/doc/toh-5/analysis_options.yaml
  examples/ng/doc/toh-5/e2e-spec.ts
  examples/ng/doc/toh-5/lib/src/dashboard_component.dart
  examples/ng/doc/toh-5/lib/src/hero_list_component.dart
  examples/ng/doc/toh-5/lib/src/routes.dart
  examples/ng/doc/toh-5/test/hero.dart
  examples/ng/doc/toh-5/test/heroes.dart
  examples/ng/doc/toh-6/analysis_options.yaml
  examples/ng/doc/toh-6/e2e-spec.ts
  examples/ng/doc/toh-6/lib/app_component.dart
  examples/ng/doc/toh-6/lib/src/dashboard_component.dart
  examples/ng/doc/toh-6/lib/src/hero_component.dart
  examples/ng/doc/toh-6/lib/src/hero_list_component.dart
  examples/ng/doc/toh-6/lib/src/hero_search_component.dart
  examples/ng/doc/toh-6/lib/src/route_paths.dart
  examples/ng/doc/toh-6/lib/src/routes.dart
  examples/ng/doc/toh-6/test/hero.dart
  examples/ng/doc/toh-6/test/heroes.dart
  src/angular/guide/testing/component/routing-components.md
  src/angular/tutorial/toh-pt5.md
  src/angular/tutorial/toh-pt6.md
Labels: Angular, Tutorials, cla: yes

#1756 Example(router): propagated toh-5 changes
  examples/ng/doc/router/lib/app_component.dart
  examples/ng/doc/router/lib/app_component_1.dart
  examples/ng/doc/router/lib/app_component_2.dart
  examples/ng/doc/router/lib/app_component_3.dart
  examples/ng/doc/router/lib/app_component_4.dart
  examples/ng/doc/router/lib/src/crisis/crisis_component.dart
  examples/ng/doc/router/lib/src/crisis/crisis_component_3.dart
  examples/ng/doc/router/lib/src/crisis/crisis_component_4.dart
  examples/ng/doc/router/lib/src/crisis/crisis_list_component.dart
  examples/ng/doc/router/lib/src/crisis/crisis_list_component.html
  examples/ng/doc/router/lib/src/crisis/crisis_list_component_3.dart
  examples/ng/doc/router/lib/src/crisis/crisis_list_component_4.dart
  examples/ng/doc/router/lib/src/crisis/route_paths.dart
  examples/ng/doc/router/lib/src/crisis/routes.dart
  examples/ng/doc/router/lib/src/hero/hero_component.dart
  examples/ng/doc/router/lib/src/hero/hero_component_0.dart
  examples/ng/doc/router/lib/src/hero/hero_list_component.dart
  examples/ng/doc/router/lib/src/hero/hero_list_component_0.dart
  examples/ng/doc/router/lib/src/route_paths.dart
  examples/ng/doc/router/lib/src/route_paths_1.dart
  examples/ng/doc/router/lib/src/routes.dart
  examples/ng/doc/router/lib/src/routes_1.dart
  examples/ng/doc/router/lib/src/routes_2.dart
  examples/ng/doc/router/lib/src/routes_3.dart
  examples/ng/doc/router/lib/src/routes_4.dart
  examples/ng/doc/toh-5/lib/app_component.dart
  examples/ng/doc/toh-5/lib/src/dashboard_component.dart
  examples/ng/doc/toh-5/lib/src/hero_component.dart
  examples/ng/doc/toh-5/lib/src/hero_list_component.dart
  examples/ng/doc/toh-5/lib/src/route_paths.dart
  examples/ng/doc/toh-5/test/hero.dart
  examples/ng/doc/toh-5/test/heroes.dart
  examples/ng/doc/toh-6/lib/src/dashboard_component.dart
  examples/ng/doc/toh-6/lib/src/hero_component.dart
  examples/ng/doc/toh-6/lib/src/hero_list_component.dart
  examples/ng/doc/toh-6/lib/src/hero_search_component.dart
  examples/ng/doc/toh-6/lib/src/route_paths.dart
  examples/ng/doc/toh-6/test/hero.dart
  examples/ng/doc/toh-6/test/heroes.dart
  src/angular/guide/router/1.md
  src/angular/guide/router/2.md
  src/angular/guide/router/3.md
  src/angular/guide/router/4.md
  src/angular/guide/router/5.md
  src/angular/guide/router/appendices.md
  src/angular/guide/router/index.md
  src/angular/tutorial/toh-pt5.md
  src/angular/tutorial/toh-pt6.md
Labels: Angular, Docs, Examples, cla: yes

#1760 Upgrade ACX to 0.9.0-beta+3, and other minor cleanup
  examples/acx/lottery/1-base/pubspec.lock
  examples/acx/lottery/2-starteasy/pubspec.lock
  examples/acx/lottery/3-usebuttons/pubspec.lock
  examples/acx/lottery/4-final/pubspec.lock
  examples/fetch_data/pubspec.lock
  examples/html/pubspec.lock
  examples/ng/api/common/pipes/pubspec.lock
  examples/ng/api/core/ngzone/pubspec.lock
  examples/ng/doc/architecture/pubspec.lock
  examples/ng/doc/attribute-directives/pubspec.lock
  examples/ng/doc/component-styles/pubspec.lock
  examples/ng/doc/dependency-injection/pubspec.lock
  examples/ng/doc/displaying-data/pubspec.lock
  examples/ng/doc/forms/pubspec.lock
  examples/ng/doc/hierarchical-dependency-injection/pubspec.lock
  examples/ng/doc/lifecycle-hooks/pubspec.lock
  examples/ng/doc/pipes/pubspec.lock
  examples/ng/doc/quickstart/pubspec.lock
  examples/ng/doc/router/pubspec.lock
  examples/ng/doc/security/pubspec.lock
  examples/ng/doc/server-communication/pubspec.lock
  examples/ng/doc/structural-directives/pubspec.lock
  examples/ng/doc/template-syntax/pubspec.lock
  examples/ng/doc/toh-0/pubspec.lock
  examples/ng/doc/toh-1/pubspec.lock
  examples/ng/doc/toh-2/pubspec.lock
  examples/ng/doc/toh-3/pubspec.lock
  examples/ng/doc/toh-4/pubspec.lock
  examples/ng/doc/toh-5/pubspec.lock
  examples/ng/doc/toh-6/pubspec.lock
  examples/ng/doc/user-input/pubspec.lock
  examples/util/pageloader/pubspec.lock
  pubspec.lock
  src/_data/pkg-vers.json
  src/_data/pubspec.lock
  src/_data/pubspec.yaml
  src/_includes/banner.html
  src/angular/guide/template-syntax.md
Labels: cla: yes

#1765 chore(dartdoc): use dartdoc from head
  gulpfile.js
  scripts/before-install.sh
Labels: Infrastructure, cla: yes

#1767 Jekyll plugin cleanup: make example_ref a tag rather than a block
  src/_plugins/example-ref.rb
  src/angular/guide/architecture.md
  src/angular/guide/attribute-directives.md
  src/angular/guide/component-styles.md
  src/angular/guide/dependency-injection.md
  src/angular/guide/displaying-data.md
  src/angular/guide/forms.md
  src/angular/guide/hierarchical-dependency-injection.md
  src/angular/guide/index.md
  src/angular/guide/lifecycle-hooks.md
  src/angular/guide/pipes.md
  src/angular/guide/router/5.md
  src/angular/guide/router/index.md
  src/angular/guide/security.md
  src/angular/guide/server-communication.md
  src/angular/guide/structural-directives.md
  src/angular/guide/template-syntax.md
  src/angular/guide/user-input.md
  src/angular/tutorial/index.md
  src/angular/tutorial/toh-pt0.md
  src/angular/tutorial/toh-pt1.md
  src/angular/tutorial/toh-pt2.md
  src/angular/tutorial/toh-pt3.md
  src/angular/tutorial/toh-pt4.md
  src/angular/tutorial/toh-pt5.md
  src/angular/tutorial/toh-pt6.md
Labels: Infrastructure, cla: yes

#1769 Examples: drop deprecated materialDirectives; ACX codelab cleanup
  examples/acx/lottery/1-base/lib/lottery_simulator.dart
  examples/acx/lottery/1-base/lib/lottery_simulator.html
  examples/acx/lottery/1-base/pubspec.lock
  examples/acx/lottery/1-base/pubspec.yaml
  examples/acx/lottery/1-base/test/app_test.dart
  examples/acx/lottery/1-base/web/index.html
  examples/acx/lottery/2-starteasy/lib/lottery_simulator.dart
  examples/acx/lottery/2-starteasy/lib/src/help/help.dart
  examples/acx/lottery/2-starteasy/pubspec.lock
  examples/acx/lottery/2-starteasy/pubspec.yaml
  examples/acx/lottery/2-starteasy/test/app_test.dart
  examples/acx/lottery/2-starteasy/web/index.html
  examples/acx/lottery/3-usebuttons/lib/lottery_simulator.dart
  examples/acx/lottery/3-usebuttons/lib/src/help/help.dart
  examples/acx/lottery/3-usebuttons/pubspec.lock
  examples/acx/lottery/3-usebuttons/pubspec.yaml
  examples/acx/lottery/3-usebuttons/test/app_test.dart
  examples/acx/lottery/3-usebuttons/web/index.html
  examples/acx/lottery/4-final/lib/lottery_simulator.dart
  examples/acx/lottery/4-final/lib/src/help/help.dart
  examples/acx/lottery/4-final/pubspec.lock
  examples/acx/lottery/4-final/pubspec.yaml
  examples/acx/lottery/4-final/test/app_test.dart
  examples/acx/lottery/4-final/web/index.html
  examples/ng/doc/router/lib/src/hero/hero_component_0.dart
  examples/ng/doc/structural-directives/lib/app_component.dart
  examples/ng/doc/structural-directives/pubspec.lock
  examples/ng/doc/template-syntax/lib/app_component.dart
  examples/ng/doc/template-syntax/pubspec.lock
  examples/ng/doc/template-syntax/test/app_test.dart
  gulp/test.js
  src/_codelabs/angular_components/1-base.md
  src/_codelabs/angular_components/2-starteasy.md
  src/_codelabs/angular_components/3-usebuttons.md
  src/_codelabs/angular_components/4-final.md
  src/_codelabs/angular_components/_run_example.md
  src/_codelabs/angular_components/index.md
  src/_plugins/example-ref.rb
Labels: cla: yes

#1772 Drop dartdoc workaround
  examples/acx/lottery/4-final/pubspec.lock
  examples/fetch_data/pubspec.lock
  examples/html/pubspec.lock
  examples/ng/api/common/pipes/pubspec.lock
  examples/ng/api/core/ngzone/pubspec.lock
  examples/ng/doc/architecture/pubspec.lock
  examples/ng/doc/attribute-directives/pubspec.lock
  examples/ng/doc/component-styles/pubspec.lock
  examples/ng/doc/dependency-injection/pubspec.lock
  examples/ng/doc/displaying-data/pubspec.lock
  examples/ng/doc/forms/pubspec.lock
  examples/ng/doc/hierarchical-dependency-injection/pubspec.lock
  examples/ng/doc/lifecycle-hooks/pubspec.lock
  examples/ng/doc/pipes/pubspec.lock
  examples/ng/doc/quickstart/pubspec.lock
  examples/ng/doc/router/pubspec.lock
  examples/ng/doc/security/pubspec.lock
  examples/ng/doc/server-communication/pubspec.lock
  examples/ng/doc/toh-0/pubspec.lock
  examples/ng/doc/toh-1/pubspec.lock
  examples/ng/doc/toh-2/pubspec.lock
  examples/ng/doc/toh-3/pubspec.lock
  examples/ng/doc/toh-4/pubspec.lock
  examples/ng/doc/toh-5/pubspec.lock
  examples/ng/doc/toh-6/pubspec.lock
  examples/ng/doc/user-input/pubspec.lock
  pubspec.lock
  scripts/before-install.sh
  src/_data/pubspec.lock
Labels: Infrastructure, cla: yes

#1776 Note that angular_components doesn't support IE.
  src/components/index.md
Labels: cla: yes

#1782 Update Angular news
  src/angular/index.md
Labels: cla: yes

#1785 code_excerpt_processor.rb: eliminate direct use of code-example directive
  src/_plugins/code_excerpt_processor.rb
Labels: Infrastructure, cla: yes

#1787 Update the FAQ
  src/faq.md
  src/tools/webdev.md
Labels: cla: yes

#1790 Add update info to the webdev page
  src/tools/webdev.md
Labels: cla: yes

#1792 Reinstate link checking, and refresh submodules
  scripts/before-install.sh
  scripts/check-after-site-build.sh
Labels: Infrastructure, cla: yes

#1800 Cleanup: drop unused images and styles.scss placeholder
  .gitignore
  src/_assets/images/angular_components_example-screenshot.png
  src/_assets/images/green-run.png
  src/_assets/images/ng/devguide/animations/ng_animate_transitions_inactive_active.png
  src/_assets/images/ng/devguide/animations/ng_animate_transitions_inactive_active_void.png
  src/_assets/images/ng/devguide/animations/ng_animate_transitions_inactive_active_wildcards.png
  src/_assets/images/ng/devguide/animations/ng_animate_transitions_void_in.png
  src/_assets/images/ng/devguide/architecture/airplane.png
  src/_assets/images/ng/devguide/architecture/modules.png
  src/_assets/images/ng/devguide/architecture/overview.png
  src/_assets/images/ng/devguide/forms/hero-form-cleared.png
  src/_assets/images/ng/devguide/pipes/power-boost-calculator.png
  src/_assets/images/ng/devguide/quickstart/quickstart-plnkr-big.png
  src/_assets/images/ng/devguide/quickstart/quickstart-plnkr.png
  src/_assets/images/ng/devguide/router/complete-nav.png
  src/_assets/images/ng/devguide/router/confirm-dialog.png
  src/_assets/images/ng/devguide/router/contact-popup.png
  src/_assets/images/ng/devguide/router/crisis-center-detail-2-tab.png
  src/_assets/images/ng/devguide/router/crisis-center-detail.png
  src/_assets/images/ng/devguide/router/crisis-center-list-2-tab.png
  src/_assets/images/ng/devguide/router/crisis-center-list.png
  src/_assets/images/ng/devguide/router/hero-detail-2-tab.png
  src/_assets/images/ng/devguide/router/hero-detail.png
  src/_assets/images/ng/devguide/router/hero-list-2-tab.png
  src/_assets/images/ng/devguide/router/hero-list.png
  src/_assets/images/ng/devguide/router/selected-crisis.png
  src/_assets/images/ng/devguide/router/selected-hero-old.png
  src/_assets/images/ng/devguide/security/bypass-security-component-old.png
  src/_assets/images/ng/devguide/security/bypass-security-component.jpg
  src/_assets/images/ng/devguide/server-communication/hero-list.png
  src/_assets/images/ng/devguide/structural-directives/myUnless-is-true.png
  src/_assets/images/ng/devguide/structural-directives/ngIf-and-myUnless.png
  src/_assets/images/ng/devguide/structural-directives/ngSwitch-rendering.png
  src/_assets/images/ng/devguide/structural-directives/template-in-out-of-a2.png
  src/_assets/images/ng/devguide/toh/hero-details-save-button.png
  src/_assets/images/ng/devguide/toh/heroes-list-delete-button.png
  src/_assets/images/ng/devguide/user-input/little-tour.png
  src/_assets/images/ng/heroes.png
  src/_assets/stylesheets/style.scss
  src/_includes/head.html
Labels: Infrastructure, cla: yes

#1803 Reorder items in codelabs page
  src/_codelabs/index.md
Labels: cla: yes

#1804 Make clear that dartdevc supports only Chrome
  .gitignore
  src/_assets/css/_code.scss
  src/_data/side-nav.yml
  src/_guides/get-started.md
  src/angular/guide/setup.md
  src/faq.md
  src/tools/webdev.md
Labels: cla: yes

#1809 Fixed a typo
  src/angular/note/faq/component-loading.md
Labels: cla: yes

#1810 Tweak Get Started page
  src/_guides/get-started.md
  src/_includes/webstorm-status.md
  src/_tutorials/low-level-html/connect-dart-html.md
Labels: cla: yes
