Repository dart-lang/site-webdev, pull requests merged in 2018-05, with the labels that each got.

#1564 Upgrade SDK to 2-dev.52
  examples/acx/lottery/1-base/pubspec.lock
  examples/acx/lottery/2-starteasy/pubspec.lock
  examples/acx/lottery/3-usebuttons/pubspec.lock
  examples/acx/lottery/4-final/pubspec.lock
  examples/ng/api/common/pipes/pubspec.lock
  examples/ng/api/core/ngzone/pubspec.lock
  examples/ng/doc/architecture/pubspec.lock
  examples/ng/doc/attribute-directives/pubspec.lock
  examples/ng/doc/component-styles/pubspec.lock
  examples/ng/doc/dependency-injection/pubspec.lock
  examples/ng/doc/displaying-data/pubspec.lock
  examples/ng/doc/forms/pubspec.lock
  examples/ng/doc/hierarchical-dependency-injection/pubspec.lock
  examples/ng/doc/lifecycle-hooks/pubspec.lock
  examples/ng/doc/pipes/pubspec.lock
  examples/ng/doc/quickstart/pubspec.lock
  examples/ng/doc/router/pubspec.lock
  examples/ng/doc/security/pubspec.lock
  examples/ng/doc/server-communication/pubspec.lock
  examples/ng/doc/structural-directives/pubspec.lock
  examples/ng/doc/template-syntax/pubspec.lock
  examples/ng/doc/toh-0/pubspec.lock
  examples/ng/doc/toh-1/pubspec.lock
  examples/ng/doc/toh-2/pubspec.lock
  examples/ng/doc/toh-3/pubspec.lock
  examples/ng/doc/toh-4/pubspec.lock
  examples/ng/doc/toh-5/pubspec.lock
  examples/ng/doc/toh-6/pubspec.lock
  examples/ng/doc/user-input/pubspec.lock
  examples/util/pageloader/pubspec.lock
  src/_data/pkg-vers.json
  src/_data/pubspec.lock
Labels: cla: yes

#1568 Dart 2 migration guide: fix example source diffs
  src/dart-2.md
Labels: cla: yes

#1574 Examples index page
  src/examples.md
Labels: Examples, cla: yes

#1583 chore: adjust URL to site-shared
  .gitmodules
Labels: Infrastructure, cla: yes

#1579 Document webdev tool, add build_runner test cmd description
  gulp/e2e.js
  gulpfile.js
  scripts/before-install.sh
  src/_codelabs/angular_components/1-base.md
  src/_includes/location-strategy-callout.md
  src/_tutorials/low-level-html/connect-dart-html.md
  src/angular/guide/deployment.md
  src/angular/guide/setup.md
  src/angular/guide/testing/component/running-tests.md
  src/angular/tutorial/toh-pt1.md
  src/changelog.md
  src/dart-2.md
  src/tools/build_runner.md
  src/tools/dart2js.md
  src/tools/dartdevc/faq.md
  src/tools/dartdevc/index.md
  src/tools/index.md
  src/tools/webdev.md
Labels: cla: yes

#1588 Get started: fix image position
  src/_guides/get-started.md
Labels: cla: yes

#1590 Update README.md
  README.md
Labels: cla: yes

#1591 Upgrade to SDK 2-dev.55
  .travis.yml
  examples/acx/lottery/1-base/pubspec.lock
  examples/acx/lottery/2-starteasy/pubspec.lock
  examples/acx/lottery/3-usebuttons/pubspec.lock
  examples/acx/lottery/4-final/pubspec.lock
  examples/ng/api/common/pipes/pubspec.lock
  examples/ng/api/core/ngzone/pubspec.lock
  examples/ng/doc/architecture/pubspec.lock
  examples/ng/doc/attribute-directives/pubspec.lock
  examples/ng/doc/component-styles/pubspec.lock
  examples/ng/doc/dependency-injection/pubspec.lock
  examples/ng/doc/displaying-data/pubspec.lock
  examples/ng/doc/forms/pubspec.lock
  examples/ng/doc/hierarchical-dependency-injection/pubspec.lock
  examples/ng/doc/lifecycle-hooks/pubspec.lock
  examples/ng/doc/pipes/pubspec.lock
  examples/ng/doc/quickstart/pubspec.lock
  examples/ng/doc/router/pubspec.lock
  examples/ng/doc/security/pubspec.lock
  examples/ng/doc/server-communication/pubspec.lock
  examples/ng/doc/structural-directives/pubspec.lock
  examples/ng/doc/template-syntax/pubspec.lock
  examples/ng/doc/toh-0/pubspec.lock
  examples/ng/doc/toh-1/pubspec.lock
  examples/ng/doc/toh-2/pubspec.lock
  examples/ng/doc/toh-3/pubspec.lock
  examples/ng/doc/toh-4/pubspec.lock
  examples/ng/doc/toh-5/pubspec.lock
  examples/ng/doc/toh-6/pubspec.lock
  examples/ng/doc/user-input/pubspec.lock
  examples/util/pageloader/pubspec.lock
  src/_data/pkg-vers.json
  src/_data/pubspec.lock
Labels: Examples, cla: yes

#1593 Update webdev preview site's banner
  src/_includes/banner.html
Labels: cla: yes

#1596 Tweak webdev tools page
  src/tools/index.md
Labels: cla: yes

#1602 [4.x] May 2018 survey banner
  src/_assets/stylesheets/main.scss
  src/_includes/banner-top.md
  src/_includes/banner.html
  src/index.html
Labels: Design, cla: yes

#1604 Upgrade SDK (2-dev.57) and Angular (alpha+12)
  .travis.yml
  examples/acx/lottery/1-base/pubspec.lock
  examples/acx/lottery/2-starteasy/pubspec.lock
  examples/acx/lottery/3-usebuttons/pubspec.lock
  examples/acx/lottery/4-final/pubspec.lock
  examples/ng/api/common/pipes/pubspec.lock
  examples/ng/api/core/ngzone/pubspec.lock
  examples/ng/doc/architecture/lib/src/sales_tax_component.dart
  examples/ng/doc/architecture/pubspec.lock
  examples/ng/doc/attribute-directives/pubspec.lock
  examples/ng/doc/component-styles/pubspec.lock
  examples/ng/doc/dependency-injection/pubspec.lock
  examples/ng/doc/displaying-data/pubspec.lock
  examples/ng/doc/forms/pubspec.lock
  examples/ng/doc/hierarchical-dependency-injection/pubspec.lock
  examples/ng/doc/lifecycle-hooks/pubspec.lock
  examples/ng/doc/pipes/pubspec.lock
  examples/ng/doc/quickstart/pubspec.lock
  examples/ng/doc/router/lib/src/crisis/crisis_component.html
  examples/ng/doc/router/pubspec.lock
  examples/ng/doc/security/pubspec.lock
  examples/ng/doc/server-communication/pubspec.lock
  examples/ng/doc/structural-directives/pubspec.lock
  examples/ng/doc/template-syntax/pubspec.lock
  examples/ng/doc/toh-0/pubspec.lock
  examples/ng/doc/toh-1/pubspec.lock
  examples/ng/doc/toh-2/pubspec.lock
  examples/ng/doc/toh-3/pubspec.lock
  examples/ng/doc/toh-4/pubspec.lock
  examples/ng/doc/toh-5/pubspec.lock
  examples/ng/doc/toh-5/pubspec.yaml
  examples/ng/doc/toh-5/test/dashboard.dart
  examples/ng/doc/toh-5/test/heroes.dart
  examples/ng/doc/toh-5/test/heroes_po.dart
  examples/ng/doc/toh-6/pubspec.lock
  examples/ng/doc/toh-6/pubspec.yaml
  examples/ng/doc/toh-6/test/dashboard.dart
  examples/ng/doc/toh-6/test/hero_search.dart
  examples/ng/doc/toh-6/test/heroes.dart
  examples/ng/doc/toh-6/test/heroes_po.dart
  examples/ng/doc/user-input/pubspec.lock
  examples/util/pageloader/pubspec.lock
  src/_data/pkg-vers.json
  src/_data/pubspec.lock
  src/_data/pubspec.yaml
  src/angular/guide/router/5.md
Labels: Examples, cla: yes

#1606 Get started: describe how to use CLI
  _config.yml
  src/_assets/stylesheets/_icons.scss
  src/_guides/get-started.md
  src/tools/build_runner.md
  src/tools/webdev.md
Labels: Docs, cla: yes

#1608 Remove survey announcement
  src/_includes/banner.html
  src/index.html
Labels: cla: yes

#1609 [4.x] Remove survey announcement
  src/_includes/banner.html
  src/index.html
Labels: cla: yes

#1613 Examples(lottery): ensure use of latest ACX
  examples/acx/lottery/1-base/pubspec.lock
  examples/acx/lottery/2-starteasy/pubspec.lock
  examples/acx/lottery/2-starteasy/pubspec.yaml
  examples/acx/lottery/3-usebuttons/pubspec.lock
  examples/acx/lottery/3-usebuttons/pubspec.yaml
  examples/acx/lottery/4-final/pubspec.lock
  examples/acx/lottery/4-final/pubspec.yaml
  src/_codelabs/angular_components/2-starteasy.md
Labels: ACX, Examples, cla: yes

#1617 Examples: fix code excerpt regions
  examples/ng/doc/forms/lib/src/hero_form_component_4.html
  examples/ng/doc/hierarchical-dependency-injection/lib/src/hero_tax_return_component.dart
  examples/ng/doc/server-communication/lib/in_memory_data_service.dart
  examples/ng/doc/server-communication/lib/src/toh/hero_service.dart
  examples/ng/doc/toh-1/lib/app_component.dart
  examples/ng/doc/toh-2/lib/app_component.dart
  examples/ng/doc/toh-3/test/hero_detail_test.dart
  examples/ng/doc/toh-5/lib/src/hero_list_component.dart
  examples/ng/doc/toh-6/lib/in_memory_data_service.dart
  gulp/example-frag.js
  scripts/refresh-code-excerpts.sh
  src/_guides/html-library-tour.md
  src/angular/guide/hierarchical-dependency-injection.md
  src/angular/guide/server-communication.md
  src/angular/guide/testing/component/routing-components.md
Labels: Examples, cla: yes
