Repository dart-lang/site-webdev, pull requests merged in 2018-04, with the labels that each got.

#1452 Improve links for /tools/build_runner
  firebase.json
  src/dart-2.md
Labels: cla: yes

#1454 [5-dev] Upgrade SDK to 2-dev.44
  examples/acx/lottery/1-base/pubspec.lock
  examples/acx/lottery/2-starteasy/pubspec.lock
  examples/acx/lottery/3-usebuttons/pubspec.lock
  examples/acx/lottery/4-final/pubspec.lock
  examples/ng/api/common/pipes/pubspec.lock
  examples/ng/api/core/ngzone/pubspec.lock
  examples/ng/doc/architecture/pubspec.lock
  examples/ng/doc/attribute-directives/pubspec.lock
  examples/ng/doc/component-styles/pubspec.lock
  examples/ng/doc/dependency-injection/pubspec.lock
  examples/ng/doc/displaying-data/pubspec.lock
  examples/ng/doc/forms/pubspec.lock
  examples/ng/doc/hierarchical-dependency-injection/pubspec.lock
  examples/ng/doc/lifecycle-hooks/pubspec.lock
  examples/ng/doc/pipes/pubspec.lock
  examples/ng/doc/quickstart/pubspec.lock
  examples/ng/doc/router/pubspec.lock
  examples/ng/doc/security/pubspec.lock
  examples/ng/doc/server-communication/pubspec.lock
  examples/ng/doc/structural-directives/pubspec.lock
  examples/ng/doc/template-syntax/pubspec.lock
  examples/ng/doc/toh-0/pubspec.lock
  examples/ng/doc/toh-1/pubspec.lock
  examples/ng/doc/toh-2/pubspec.lock
  examples/ng/doc/toh-3/pubspec.lock
  examples/ng/doc/toh-4/pubspec.lock
  examples/ng/doc/toh-5/pubspec.lock
  examples/ng/doc/toh-6/pubspec.lock
  examples/ng/doc/user-input/pubspec.lock
  examples/util/pageloader/pubspec.lock
  src/_data/pkg-vers.json
  src/_data/pubspec.lock
  src/_data/pubspec.yaml
Labels: Examples, Infrastructure, cla: yes

#1462 Point people from /dart-2 to v5's /dart-2 page
  src/dart-2.md
Labels: cla: yes

#1463 [5-dev] Adjust pages referring to build_runner
  src/dart-2.md
  src/tools/build_runner.md
Labels: cla: yes

#1465 [5-dev] Router: describe CanNavigate hook
  _config.yml
  examples/ng/doc/router/lib/src/crisis/crisis_component.dart
  src/angular/guide/router/1.md
  src/angular/guide/router/2.md
  src/angular/guide/router/3.md
  src/angular/guide/router/4.md
  src/angular/guide/router/5.md
  src/angular/guide/router/6.md
  src/angular/guide/router/appendices.md
  src/angular/guide/router/index.md
Labels: cla: yes

#1473 [4.x] Branch config
  .gitignore
  .travis.yml
  _config.yml
  src/_data/pkg-vers.json
  src/_includes/navigation-main.html
  src/changelog.md
Labels: cla: yes

#1475 Config changes before merging 5-dev into master
  .travis.yml
  _config.yml
  src/_includes/navigation-main.html
Labels: Infrastructure, cla: yes

#1477 AngularDart main nav dropdown: fix URL to 4.x server
  _config.yml
  src/_includes/navigation-main.html
Labels: cla: yes

#1478 Upgrade to Angular 5-alpha+10, ACX 0.9.0-alpha+10
  .travis.yml
  examples/acx/lottery/1-base/pubspec.lock
  examples/acx/lottery/2-starteasy/pubspec.lock
  examples/acx/lottery/3-usebuttons/pubspec.lock
  examples/acx/lottery/4-final/pubspec.lock
  examples/ng/api/common/pipes/pubspec.lock
  examples/ng/api/core/ngzone/pubspec.lock
  examples/ng/doc/architecture/pubspec.lock
  examples/ng/doc/attribute-directives/pubspec.lock
  examples/ng/doc/component-styles/pubspec.lock
  examples/ng/doc/dependency-injection/pubspec.lock
  examples/ng/doc/displaying-data/pubspec.lock
  examples/ng/doc/forms/pubspec.lock
  examples/ng/doc/hierarchical-dependency-injection/pubspec.lock
  examples/ng/doc/lifecycle-hooks/pubspec.lock
  examples/ng/doc/pipes/pubspec.lock
  examples/ng/doc/quickstart/pubspec.lock
  examples/ng/doc/router/pubspec.lock
  examples/ng/doc/security/pubspec.lock
  examples/ng/doc/server-communication/pubspec.lock
  examples/ng/doc/structural-directives/pubspec.lock
  examples/ng/doc/template-syntax/pubspec.lock
  examples/ng/doc/toh-0/pubspec.lock
  examples/ng/doc/toh-1/pubspec.lock
  examples/ng/doc/toh-2/pubspec.lock
  examples/ng/doc/toh-3/pubspec.lock
  examples/ng/doc/toh-4/pubspec.lock
  examples/ng/doc/toh-5/pubspec.lock
  examples/ng/doc/toh-6/pubspec.lock
  examples/ng/doc/user-input/pubspec.lock
  examples/util/pageloader/pubspec.lock
  scripts/config/linkcheck-skip-list.txt
  src/_data/pkg-vers.json
  src/_data/pubspec.lock
  src/_data/pubspec.yaml
Labels: Angular, Examples, cla: yes

#1482 Update toh-6 component tests to use static DI
  examples/ng/doc/toh-5/lib/src/dashboard_component.css
  examples/ng/doc/toh-5/lib/src/dashboard_component.dart
  examples/ng/doc/toh-5/test/all_test.dart
  examples/ng/doc/toh-5/test/hero.dart
  examples/ng/doc/toh-5/test/heroes.dart
  examples/ng/doc/toh-5/test/heroes_po.dart
  examples/ng/doc/toh-6/lib/app_component.dart
  examples/ng/doc/toh-6/lib/src/dashboard_component.dart
  examples/ng/doc/toh-6/lib/src/dashboard_component.html
  examples/ng/doc/toh-6/lib/src/hero_component.dart
  examples/ng/doc/toh-6/lib/src/hero_list_component.html
  examples/ng/doc/toh-6/lib/src/hero_search_component.dart
  examples/ng/doc/toh-6/test/all_test.dart
  examples/ng/doc/toh-6/test/app.dart
  examples/ng/doc/toh-6/test/app_po.dart
  examples/ng/doc/toh-6/test/app_test.dart
  examples/ng/doc/toh-6/test/dashboard.dart
  examples/ng/doc/toh-6/test/hero.dart
  examples/ng/doc/toh-6/test/hero_po.dart
  examples/ng/doc/toh-6/test/hero_search.dart
  examples/ng/doc/toh-6/test/heroes.dart
  examples/ng/doc/toh-6/test/heroes_po.dart
  examples/ng/doc/toh-6/test/matchers.dart
  examples/ng/doc/toh-6/test/utils.dart
  src/angular/guide/testing/component/simulating-user-action.md
  src/angular/tutorial/toh-pt3.md
  src/angular/tutorial/toh-pt4.md
  src/angular/tutorial/toh-pt5.md
  src/angular/tutorial/toh-pt6.md
Labels: Angular, Examples, Tests, Tutorials, cla: yes

#1485 Examples(architecture, attribute-directives, component-styles): use static DI
  examples/ng/doc/architecture/lib/app_component.dart
  examples/ng/doc/architecture/lib/src/hero_list_component.dart
  examples/ng/doc/architecture/lib/src/sales_tax_component.dart
  examples/ng/doc/architecture/pubspec.yaml
  examples/ng/doc/architecture/web/main.dart
  examples/ng/doc/attribute-directives/web/main.dart
  examples/ng/doc/component-styles/lib/app_component.dart
  examples/ng/doc/component-styles/web/main.dart
  src/angular/guide/architecture.md
  src/angular/guide/component-styles.md
Labels: Angular, Examples, cla: yes

#1487 Clarify branches for pull requests
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla: yes

#1486 Remove non-webdev codelab from /codelabs
  src/_codelabs/index.md
Labels: cla: yes

#1493 Upgrade to SDK 2-dev.48
  examples/acx/lottery/1-base/pubspec.lock
  examples/acx/lottery/2-starteasy/pubspec.lock
  examples/acx/lottery/3-usebuttons/pubspec.lock
  examples/acx/lottery/4-final/pubspec.lock
  examples/ng/api/common/pipes/pubspec.lock
  examples/ng/api/core/ngzone/pubspec.lock
  examples/ng/doc/architecture/pubspec.lock
  examples/ng/doc/attribute-directives/pubspec.lock
  examples/ng/doc/component-styles/pubspec.lock
  examples/ng/doc/dependency-injection/pubspec.lock
  examples/ng/doc/displaying-data/pubspec.lock
  examples/ng/doc/forms/pubspec.lock
  examples/ng/doc/hierarchical-dependency-injection/pubspec.lock
  examples/ng/doc/lifecycle-hooks/pubspec.lock
  examples/ng/doc/pipes/pubspec.lock
  examples/ng/doc/quickstart/pubspec.lock
  examples/ng/doc/router/pubspec.lock
  examples/ng/doc/security/pubspec.lock
  examples/ng/doc/server-communication/pubspec.lock
  examples/ng/doc/structural-directives/pubspec.lock
  examples/ng/doc/template-syntax/pubspec.lock
  examples/ng/doc/toh-0/pubspec.lock
  examples/ng/doc/toh-1/pubspec.lock
  examples/ng/doc/toh-2/pubspec.lock
  examples/ng/doc/toh-3/pubspec.lock
  examples/ng/doc/toh-4/pubspec.lock
  examples/ng/doc/toh-5/pubspec.lock
  examples/ng/doc/toh-6/pubspec.lock
  examples/ng/doc/user-input/pubspec.lock
  examples/util/pageloader/pubspec.lock
  src/_data/pkg-vers.json
  src/_data/pubspec.lock
  src/_data/pubspec.yaml
Labels: Infrastructure, cla: yes

#1500 Ensure apps are copied from gh-pages branch to deploy folder
  gulp/example-add-apps.js
  gulpfile.js
Labels: Examples, Infrastructure, cla: yes

#1501 Example app deployment: redistribute tasks to appropriate stages
  .travis.yml
  gulp/example-add-apps.js
  gulpfile.js
Labels: Infrastructure, cla: yes

#1502 chore(sitemap): fix API URLs
  src/sitemap.xml
Labels: Infrastructure, cla: yes

#1504 Examples: use static DI and runApp()
  examples/acx/lottery/1-base/lib/lottery_simulator.dart
  examples/acx/lottery/1-base/web/main.dart
  examples/acx/lottery/2-starteasy/lib/lottery_simulator.dart
  examples/acx/lottery/2-starteasy/web/main.dart
  examples/acx/lottery/3-usebuttons/lib/lottery_simulator.dart
  examples/acx/lottery/3-usebuttons/web/main.dart
  examples/acx/lottery/4-final/lib/lottery_simulator.dart
  examples/acx/lottery/4-final/web/main.dart
  examples/ng/doc/displaying-data/web/main.dart
  examples/ng/doc/forms/web/main.dart
  examples/ng/doc/lifecycle-hooks/lib/app_component.dart
  examples/ng/doc/lifecycle-hooks/lib/src/after_content_component.dart
  examples/ng/doc/lifecycle-hooks/lib/src/after_view_component.dart
  examples/ng/doc/lifecycle-hooks/lib/src/counter_component.dart
  examples/ng/doc/lifecycle-hooks/lib/src/peek_a_boo_parent_component.dart
  examples/ng/doc/lifecycle-hooks/lib/src/spy_component.dart
  examples/ng/doc/lifecycle-hooks/web/main.dart
  examples/ng/doc/pipes/web/main.dart
  examples/ng/doc/security/web/main.dart
  examples/ng/doc/server-communication/lib/in_memory_data_service.dart
  examples/ng/doc/server-communication/web/main.dart
  examples/ng/doc/server-communication/web/main_1.dart
  examples/ng/doc/structural-directives/lib/app_component.html
  examples/ng/doc/structural-directives/web/main.dart
  examples/ng/doc/template-syntax/lib/app_component.html
  examples/ng/doc/template-syntax/lib/src/sizer_component.dart
  examples/ng/doc/template-syntax/pubspec.yaml
  examples/ng/doc/template-syntax/test/sizer_po.dart
  examples/ng/doc/template-syntax/web/main.dart
  examples/ng/doc/user-input/web/main.dart
  src/_codelabs/angular_components/2-starteasy.md
  src/angular/guide/displaying-data.md
  src/angular/guide/server-communication.md
  src/angular/guide/template-syntax.md
Labels: Angular, Examples, cla: yes

#1503 Changelog: mention runApp() and compile-time DI
  examples/ng/doc/dependency-injection/lib/src/providers_component.dart
  examples/ng/doc/toh-5/web/main.dart
  src/changelog.md
Labels: cla: yes

#1507 Example(hierarchical-DI): switch to using runApp()
  examples/ng/doc/hierarchical-dependency-injection/lib/src/car_components.dart
  examples/ng/doc/hierarchical-dependency-injection/lib/src/hero_tax_return_component.dart
  examples/ng/doc/hierarchical-dependency-injection/lib/src/villains_list_component.dart
  examples/ng/doc/hierarchical-dependency-injection/lib/src/villains_service.dart
  examples/ng/doc/hierarchical-dependency-injection/web/main.dart
  src/angular/guide/hierarchical-dependency-injection.md
Labels: Angular, cla: yes

#1508 Cleanup links: drop .html from intrasite links
  src/angular/guide/architecture.md
  src/angular/guide/attribute-directives.md
  src/angular/guide/displaying-data.md
  src/angular/guide/forms.md
  src/angular/guide/index.md
  src/angular/guide/learning-angular.md
  src/angular/guide/lifecycle-hooks.md
  src/angular/guide/pipes.md
  src/angular/guide/router/5.md
  src/angular/guide/router/appendices.md
  src/angular/guide/router/index.md
  src/angular/guide/setup.md
  src/angular/guide/structural-directives.md
  src/angular/guide/template-syntax.md
  src/angular/tutorial/toh-pt0.md
  src/angular/tutorial/toh-pt1.md
  src/angular/tutorial/toh-pt2.md
  src/angular/tutorial/toh-pt3.md
  src/angular/tutorial/toh-pt4.md
Labels: Docs, cla: yes

#1506 Cheatsheet bootstrap -> runApp() + static DI
  src/_assets/stylesheets/main.scss
  src/angular/cheatsheet/_bootstrapping.md
  src/angular/cheatsheet/index.md
Labels: Angular, Docs, cla: yes

#1511 Example(toh-1): clarify change to `hero` field
  examples/ng/doc/toh-1/lib/app_component_2.dart
  src/angular/tutorial/toh-pt1.md
Labels: Angular, Tutorials, cla: yes

#1509 Remove references to bootstrapping where appropriate
  scripts/config/linkcheck-skip-list.txt
  src/_articles/low-level-html/embedding-in-html.md
  src/_guides/web-programming.md
  src/_tutorials/get-data/fetch-data.md
  src/_tutorials/index.md
  src/angular/glossary.md
  src/angular/guide/architecture.md
  src/angular/guide/component-styles.md
  src/angular/guide/dependency-injection.md
  src/angular/guide/displaying-data.md
  src/angular/guide/forms.md
  src/angular/guide/hierarchical-dependency-injection.md
  src/angular/guide/index.md
  src/angular/guide/learning-angular.md
  src/angular/guide/lifecycle-hooks.md
  src/angular/guide/pipes.md
  src/angular/guide/router/appendices.md
  src/angular/guide/router/index.md
  src/angular/guide/security.md
  src/angular/guide/server-communication.md
  src/angular/guide/template-syntax.md
  src/angular/guide/testing/component/routing-components.md
  src/angular/tutorial/toh-pt0.md
  src/changelog.md
  src/faq.md
Labels: Angular, Docs, cla: yes

#1514 Examples: merge DDS boilerplate; generalize and simplify boilerplate setup code
  .gitignore
  examples/_boilerplate/.gitignore
  examples/_boilerplate/LICENSE
  examples/_boilerplate/web/favicon.png
  examples/ng/doc/.gitignore
  examples/ng/doc/_boilerplate/web/styles.css
  gulp/e2e.js
  gulp/example.js
  gulpfile.js
  package-lock.json
  package.json
  src/angular/tutorial/toh-pt0.md
  src/angular/tutorial/toh-pt5.md
Labels: Infrastructure, cla: yes

#1517 Upgrade Dart SDK to 2-dev.49; skip failing E2E
  .travis.yml
  examples/acx/lottery/1-base/pubspec.lock
  examples/acx/lottery/2-starteasy/pubspec.lock
  examples/acx/lottery/3-usebuttons/pubspec.lock
  examples/acx/lottery/4-final/pubspec.lock
  examples/ng/api/common/pipes/pubspec.lock
  examples/ng/api/core/ngzone/pubspec.lock
  examples/ng/doc/architecture/pubspec.lock
  examples/ng/doc/attribute-directives/pubspec.lock
  examples/ng/doc/component-styles/pubspec.lock
  examples/ng/doc/dependency-injection/pubspec.lock
  examples/ng/doc/displaying-data/pubspec.lock
  examples/ng/doc/forms/pubspec.lock
  examples/ng/doc/hierarchical-dependency-injection/pubspec.lock
  examples/ng/doc/lifecycle-hooks/pubspec.lock
  examples/ng/doc/pipes/pubspec.lock
  examples/ng/doc/quickstart/pubspec.lock
  examples/ng/doc/router/pubspec.lock
  examples/ng/doc/security/pubspec.lock
  examples/ng/doc/server-communication/pubspec.lock
  examples/ng/doc/structural-directives/pubspec.lock
  examples/ng/doc/template-syntax/pubspec.lock
  examples/ng/doc/toh-0/pubspec.lock
  examples/ng/doc/toh-1/pubspec.lock
  examples/ng/doc/toh-2/pubspec.lock
  examples/ng/doc/toh-3/pubspec.lock
  examples/ng/doc/toh-4/pubspec.lock
  examples/ng/doc/toh-5/pubspec.lock
  examples/ng/doc/toh-6/pubspec.lock
  examples/ng/doc/user-input/pubspec.lock
  examples/util/pageloader/pubspec.lock
  src/_data/pkg-vers.json
  src/_data/pubspec.lock
  src/_data/pubspec.yaml
Labels: Infrastructure, cla: yes

#1526 chore(examples): .gitignore file cleanup
  .gitignore
  examples/.gitignore
Labels: Examples, Infrastructure, cla: yes

#1522 Router landing page fix for relative links
  src/angular/guide/router/index.md
Labels: cla: yes

#1527 [4.x] chore(examples): .gitignore file cleanup
  .gitignore
  examples/.gitignore
Labels: cla: yes

#1528 Examples: use pageloader mock from master
  examples/ng/doc/template-syntax/pubspec.yaml
  examples/ng/doc/toh-1/pubspec.yaml
  examples/ng/doc/toh-2/pubspec.yaml
  examples/ng/doc/toh-3/pubspec.yaml
  examples/ng/doc/toh-4/pubspec.yaml
  examples/ng/doc/toh-5/pubspec.yaml
  examples/ng/doc/toh-6/pubspec.yaml
  src/angular/guide/testing/component/page-objects.md
  src/angular/tutorial/toh-pt1.md
Labels: Examples, cla: yes

#1529 [4.x] Add "Angular 4" banner
  src/_includes/banner.html
Labels: cla: yes

#1525 dart-2 page tilte updated to "Dart 2 Migration Guide for Web Apps"
  src/dart-2.md
Labels: Docs, cla: yes

#1530 Angular 5 banner: fix URL to main site
  src/_includes/banner.html
Labels: cla: yes

#1531 [4.x] Adjust title "Dart 2 Migration Guide for Web Apps"
  src/dart-2.md
Labels: cla: yes

#1524 Document build --release and drop unnecessary builder config files
  examples/ng/doc/quickstart/build.debug.yaml
  examples/ng/doc/quickstart/build.release.yaml
  src/tools/build_runner.md
Labels: Docs, cla: yes

#1543 Update npm package versions
  examples/ng/doc/package-lock.json
  examples/ng/doc/package.json
  gulp/e2e.js
  package-lock.json
  package.json
Labels: Infrastructure, cla: yes

#1544 Angular tutorial part 6: don't show pageloader dep override
  examples/ng/doc/toh-6/pubspec.yaml
Labels: cla: yes

#1545 [4.x] chore: pin SDK at 1.24.3
  .travis.yml
Labels: Infrastructure, cla: yes

#1546 chore: add redirects for /tools/sdk
  firebase.json
Labels: cla: yes

#1548 Ensure that published ACX lottery apps have a base href
  examples/acx/lottery/1-base/web/index.html
  examples/acx/lottery/2-starteasy/web/index.html
  examples/acx/lottery/3-usebuttons/web/index.html
  examples/acx/lottery/4-final/web/index.html
Labels: ACX, Examples, cla: yes

#1549 Switch to pub docs for package API pages
  _config.yml
Labels: API docs, cla: yes

#1553 fix typo
  src/angular/tutorial/toh-pt5.md
Labels: Angular, Tutorials, cla: yes

#1555 Fix base href of ACX lottery examples
  gulp/example-add-apps.js
  gulpfile.js
Labels: ACX, Examples, cla: yes

#1560 Examples(analysis_options): drop 'enabled: true' for angular plugin
  examples/acx/lottery/1-base/analysis_options.yaml
  examples/acx/lottery/2-starteasy/analysis_options.yaml
  examples/acx/lottery/3-usebuttons/analysis_options.yaml
  examples/acx/lottery/4-final/analysis_options.yaml
  examples/ng/api/common/pipes/analysis_options.yaml
  examples/ng/api/core/ngzone/analysis_options.yaml
  examples/ng/doc/architecture/analysis_options.yaml
  examples/ng/doc/attribute-directives/analysis_options.yaml
  examples/ng/doc/component-styles/analysis_options.yaml
  examples/ng/doc/dependency-injection/analysis_options.yaml
  examples/ng/doc/displaying-data/analysis_options.yaml
  examples/ng/doc/forms/analysis_options.yaml
  examples/ng/doc/hierarchical-dependency-injection/analysis_options.yaml
  examples/ng/doc/lifecycle-hooks/analysis_options.yaml
  examples/ng/doc/pipes/analysis_options.yaml
  examples/ng/doc/quickstart/analysis_options.yaml
  examples/ng/doc/router/analysis_options.yaml
  examples/ng/doc/security/analysis_options.yaml
  examples/ng/doc/server-communication/analysis_options.yaml
  examples/ng/doc/structural-directives/analysis_options.yaml
  examples/ng/doc/template-syntax/analysis_options.yaml
  examples/ng/doc/toh-0/analysis_options.yaml
  examples/ng/doc/toh-1/analysis_options.yaml
  examples/ng/doc/toh-2/analysis_options.yaml
  examples/ng/doc/toh-3/analysis_options.yaml
  examples/ng/doc/toh-4/analysis_options.yaml
  examples/ng/doc/toh-5/analysis_options.yaml
  examples/ng/doc/toh-6/analysis_options.yaml
  examples/ng/doc/user-input/analysis_options.yaml
  gulp/update-ng-vers.js
Labels: Examples, cla: yes

#1561 Example analysis ignore directives cleanup
  examples/ng/doc/router/lib/src/routes_2.dart
  examples/ng/doc/toh-5/lib/src/routes.dart
  src/angular/guide/router/2.md
  src/angular/guide/router/index.md
  src/angular/tutorial/toh-pt5.md
Labels: Angular, Examples, cla: yes
