Repository dart-lang/site-webdev, pull requests merged in 2018-02, with the labels that each got.

#1314 chore(travis): cache ruby build
  .travis.yml
Labels: Infrastructure, cla: yes

#1315 chore(travis): get rvm stable only if not already latest
  scripts/get-ruby.sh
Labels: Infrastructure, cla: yes

#1316 chore(travis): use language dart
  .travis.yml
  scripts/env-set.sh
Labels: Infrastructure, cla: yes

#1317 chore(travis): use cached API docs
  .travis.yml
  gulp/dartdoc.js
  gulp/example-add-apps.js
  gulpfile.js
Labels: Infrastructure, cla: yes

#1325 chore: backport 5-dev updates
  .gitignore
  .travis.yml
  gulp/update-ng-vers.js
  gulpfile.js
  scripts/before-install.sh
  scripts/env-set.sh
  scripts/get-ruby.sh
  scripts/install.sh
  src/tools/webstorm.md
Labels: Infrastructure, cla: yes

#1326 chore: misc script cleanup
  gulp/update-ng-vers.js
  scripts/before-install.sh
  scripts/config/linkcheck-skip-list.txt
  scripts/env-set.sh
  scripts/refresh-code-excerpts.sh
Labels: Infrastructure, cla: yes

#1328 chore: upgrade ruby and gems
  Gemfile
  Gemfile.lock
  scripts/config/linkcheck-skip-list.txt
  scripts/get-ruby.sh
Labels: Infrastructure, cla: yes

#1330 chore: fixes due to breaking changes in fontawesome 5.x
  src/_codelabs/angular_components/1-base.md
  src/_codelabs/angular_components/2-starteasy.md
  src/_codelabs/angular_components/3-usebuttons.md
  src/_codelabs/angular_components/4-final.md
  src/_codelabs/angular_components/index.md
  src/_includes/page-footer.html
  src/_includes/page-github-links.html
Labels: Design, cla: yes

#1331 chore: gitignore .asset-cache no matter where it is
  .gitignore
Labels: Infrastructure, cla: yes

#1332 chore(jekyll): exclude generated Dart files and folders
  _config.yml
Labels: Infrastructure, cla: yes

#1334 chore: don't cache asset cache
  .travis.yml
Labels: Infrastructure, cla: yes

#1338 Make clear that Polymer Dart isn't supported
  src/_articles/low-level-html/embedding-in-html.md
  src/_guides/index.md
  src/_guides/polymer.md
  src/_includes/checked-mode-2.0.html
  src/_includes/dartium-2.0.html
  src/_includes/optional-types-2.0.html
  src/_tutorials/low-level-html/remove-elements.md
  src/faq.md
  src/tools/pub/pub-serve.md
Labels: cla: yes

#1341 Site version dropdown from main menu
  src/_assets/stylesheets/_overwrites.scss
  src/_assets/stylesheets/main.scss
  src/_includes/navigation-main.html
Labels: Design, cla: yes, enhancement

#1344 Main nav site-version dropdown menu tweak
  src/_includes/navigation-main.html
Labels: Infrastructure, cla: yes

#1348 Fix alert styles across webdev pages; replace callout by alert
  src/_assets/stylesheets/angular.scss
  src/_assets/stylesheets/ng/_callout.scss
  src/_assets/stylesheets/ng/ngio/module/_alert.scss
  src/_assets/stylesheets/ng/ngio/module/_callout.scss
  src/_includes/banner.html
  src/_includes/location-strategy-callout.md
  src/angular/guide/architecture.md
  src/angular/guide/component-styles.md
  src/angular/guide/dependency-injection.md
  src/angular/guide/displaying-data.md
  src/angular/guide/forms.md
  src/angular/guide/pipes.md
  src/angular/guide/router/3.md
  src/angular/guide/router/4.md
  src/angular/guide/server-communication.md
  src/angular/guide/structural-directives.md
  src/angular/guide/template-syntax.md
  src/angular/guide/testing/component/index.md
  src/angular/guide/testing/component/page-objects.md
  src/angular/guide/user-input.md
  src/angular/tutorial/toh-pt2.md
  src/angular/tutorial/toh-pt6.md
Labels: Design, cla: yes
